eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
mybatis.mapper-locations: classpath:com/wutos/AAAABBBB/domain/mapper/*.xml